services:
  go-markdown-server:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    image: ${IMAGE_NAME:-gou7ma7/go-markdown-server-with-mermaid:latest}
